# XcodeGen Project Configuration for Blab
# This file defines how to generate the Xcode project

name: Blab

options:
  bundleIdPrefix: com.blab
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.7"

targets:
  Blab:
    type: application
    platform: iOS

    # Source files location
    sources:
      - Sources/Blab

    # App settings
    settings:
      base:
        PRODUCT_NAME: Blab
        PRODUCT_BUNDLE_IDENTIFIER: com.blab.studio
        INFOPLIST_KEY_CFBundleDisplayName: Blab

        # Microphone permission
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Blab needs microphone access to create music from your voice and breath"

        # UI Configuration
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        INFOPLIST_KEY_UIUserInterfaceStyle: Dark

        # SwiftUI support
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES

        # Code signing (for development)
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: ""  # Will use your Apple ID

        # Build settings
        TARGETED_DEVICE_FAMILY: "1"  # iPhone only
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        SWIFT_VERSION: "5.7"
        ENABLE_BITCODE: NO
